spring:
  application:
    name: clinic-api
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://antonio-dev.go.ro:15884/clinicDb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    contexts: dev
    drop-first: false
    default-schema: public

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: auth.server.org@gmail.com
    password: lduqydftvyuzspoi
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:cnLbAkFva0RYi+kvpPkLCBrSCSz91CnUkYAXAvU60RoPGjTMHRiYuCaLRMVfRQ+8}
  access-token-expiration-minutes: 15
  refresh-token-expiration-days: 7

  invitation:
      expiration: PT24H

google:
  client-id: ${GOOGLE_CLIENT_ID}

frontend:
  url: http://localhost:5173

cors:
  allowed-origins: "http://localhost:5173"

clinic:
  documents:
    upload-dir: uploads/documents

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://antonio-dev.go.ro:15884/clinicDb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    contexts: prod
    drop-first: false
    default-schema: public

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.mailgun.org
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-minutes: 15
  refresh-token-expiration-days: 7

google:
  client-id: ${GOOGLE_CLIENT_ID}

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}

cors:
  allowed-origins: ${FRONTEND_URL:http://localhost:5173}

clinic:
  documents:
    upload-dir: uploads/documents
